### ISSUE TITLE
Bump of the client JS library from AngularJS to Angular

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/whistleblowing-software#3366]
This ticket is to keep track of the activities of research and development to bump the client JS library from AngularJS to Angular

Updating from angularjs to current angular would require the following:
- [ ] #3369

**Comment by msmannan00** [comment]
Now since the update is almost finished, would be posting the changes per week. sharing the github repository below
https://github.com/msmannan02/globaleaks-angular-fork

**Comment by msmannan00** [comment]
[Cypress Test Demo.webm](https://github.com/globaleaks/GlobaLeaks/assets/9531531/db49a752-c367-4063-a094-e080c3534777)

![Codacy Results](https://github.com/globaleaks/GlobaLeaks/assets/9531531/6b7d3e94-b0fe-44fb-9330-62fb529a6bad)

**Comment by msmannan02** [comment]
[Project Mappings.pdf](https://github.com/globaleaks/GlobaLeaks/files/13210448/Project.Mappings.pdf)
[project_structure.json](https://github.com/globaleaks/GlobaLeaks/files/13210451/project_structure.json)

**Comment by evilaliv3** [comment]
Closing as completed and released in 5.0.0
