### ISSUE TITLE
Voice message - Recipiente can't reproduce it

### ISSUE THREAD

**Issue by marcomeneghin** [globaleaks/whistleblowing-software#3690]
### What version of GlobaLeaks are you using?

4.13.13

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Recipient can't reproduce voice message. To reproduce he has to download file.

**Comment by marcomeneghin** [comment]
Also, is it possible to disable anonymizationo f the voice? Maybe with a flag undere the form. In this way the whistleblower can decide if he wants anonimize or not the voice.

**Comment by evilaliv3** [comment]
Thank you @marcomeneghin 

We will try to retest your setup to understand the reason of the failure and fix it.

In relation to the anonymization as the moment there is no possibility to disable it an we are evaluating the impact of making it possible to disable it.
Our doubt is that by making it possible to disable anonymizations administrators will risk to collect bio-metrical data of users that want to remain anonymous. As well enabling users to choose on this opens to similar doubts.
What do you think?

**Comment by marcomeneghin** [comment]
I'm not a lawyer but I understand your doubt.
The problem is solved by explaining in the descriptive texts that the voice is distorted and if the whistleblower intend to declare his identity he has just to start the registration by declaring his identity.

I add this issue also connected with voice message that I have already notify. Using site from smartphone: the preview box is too small and even by clicking on the three dots the menu appears all the way to the left and you can't see anything, so listening to the message again is difficult (you have to rotate the smartphone). I tried to set the field width in the questionnaire properties but the system accepts values ​​up to 10 and in any case the substance does not change.

**Comment by gianlucagilardi** [comment]
My 2c.

I fail to see why *on the whistleblower's side*  voice transcoding should be an issue which would need to be optional: if the WB wants to be anonymous, fine, that's exactly the purpose of the transcoding. If, OTOH, they want to disclose their identity, they need to do so by providing their name, contact details etc. irrespective of the (transcoded) voice *alone* which does not guarantee by itself that the individual can be identified.

While there might be cases where it can be argued that *the recipients* might have an interest in the unmodified vocal message I have a hard time imasgining an actual case in which this choice should be in the WB's hands :)

**Comment by marcomeneghin** [comment]
Hello,
  I also believe that the level of distortion is excessive, it is really difficult to understand what the reporter is saying.

Thanks, M.

Da: Javi Alamá ***@***.***>
Inviato: mercoledì 11 ottobre 2023 08:54
A: globaleaks/GlobaLeaks ***@***.***>
Cc: Marco Meneghin ***@***.***>; Mention ***@***.***>
Oggetto: Re: [globaleaks/GlobaLeaks] Voice message - Recipiente can't reproduce it (Issue #3690)


Good morning !!

After testing the new voice recording functionality, in my view, the level of distortion is so high that there is no way to understand what a whistleblower is saying.

We have tested speaking slowly, speaking loudly, leaving space between words, and there is no way, it is not possible to understand what is recorded.

Is it possible to set a distortion level for future versions?

**Comment by evilaliv3** [comment]
Thank you for all your feedback.

We are working on optimizing the algoritms to reduce the distortion

**Comment by marcomeneghin** [comment]
Hello,
  Today I restarted the server and now the recipient can listen to new messages. In the test voice messages recorded yesterday, however, the play triangle is not clickable. Is it possible that some service didn't start correctly yesterday?

  Thanks, M.

Da: Giovanni Pellerano ***@***.***>
Inviato: martedì 10 ottobre 2023 16:36
A: globaleaks/GlobaLeaks ***@***.***>
Cc: Marco Meneghin ***@***.***>; Mention ***@***.***>
Oggetto: Re: [globaleaks/GlobaLeaks] Voice message - Recipiente can't reproduce it (Issue #3690)


Thank you @marcomeneghin<https://github.com/marcomeneghin>

We will try to retest your setup to understand the reason of the failure and fix it.

In relation to the anonymization as the moment there is no possibility to disable it an we are evaluating the impact of making it possible to disable it.
Our doubt is that by making it possible to disable anonymizations administrators will risk to collect bio-metrical data of users that want to remain anonymous. As well enabling users to choose on this opens to similar doubts.
What do you think?

**Comment by evilaliv3** [comment]
@marcomeneghin: actually the bug you encountered happens on some browsers / operating systems and we are working on fixing it.

@JaviAlama @elbill : https://speakeranonymization.try.globaleaks.org/ would you please retry now? we fine tuned the algoritm to minimize distortion while applying relevant voice anonymization.
We have also tested analyzing the resulting audio with some transcription tools and the transcription tools where fully able to provide a perfect transctiption.

**Comment by marcomeneghin** [comment]
Thank you very much, is the revised audio distortion already available (uses web components) or do we have to wait for the release of the new software version?
When you think it will be done?

Due to the problem related to the impossibility of reproducing the audio for the case manager, I was no longer able to reproduce the problem, however I have some old test reports that look like this:

***@***.***

Thanks for support.

Best regards, M.


Da: Giovanni Pellerano ***@***.***>
Inviato: mercoledì 11 ottobre 2023 22:39
A: globaleaks/GlobaLeaks ***@***.***>
Cc: Marco Meneghin ***@***.***>; Mention ***@***.***>
Oggetto: Re: [globaleaks/GlobaLeaks] Voice message - Recipiente can't reproduce it (Issue #3690)


@marcomeneghin<https://github.com/marcomeneghin>: actually the bug you encountered happens on some browsers / operating systems and we are working on fixing it.

@JaviAlama<https://github.com/JaviAlama> @elbill<https://github.com/elbill> : https://speakeranonymization.try.globaleaks.org/ would you please retry now? we fine tuned the algoritm to minimize distortion while applying relevant voice anonymization.
We have also tested analyzing the resulting audio with some transcription tools and the transcription tools where fully able to provide a perfect transctiption.

**Comment by JaviAlama** [comment]
> @marcomeneghin: actually the bug you encountered happens on some browsers / operating systems and we are working on fixing it.
> 
> @JaviAlama @elbill : https://speakeranonymization.try.globaleaks.org/ would you please retry now? we fine tuned the algoritm to minimize distortion while applying relevant voice anonymization. We have also tested analyzing the resulting audio with some transcription tools and the transcription tools where fully able to provide a perfect transctiption.

Which translation tool did you use? I tested directly with my children.... and had problems to understand the audios.

**Comment by evilaliv3** [comment]
Thank you for your feeback.

@marcomeneghin : we are relesing the revised alghorithm by today.

@JaviAlama: i just tested uploading the audio on slack and it gave me back an almost perfect transcription. Of course i may have tuned the algorithm with a bias on my voice and i may have spoken clearly to the microphone.
If the community is not satisfied with the result i think the only option we have is to make it optional ad platform level to choose if audio recording should be anonymized or not but this will determine if the full reporting is anonymous or not.

**Comment by JaviAlama** [comment]
Hi Giovanni,  I agree with you, giving the option to distort or not the audio might be the best option. My boss is testing the tool and I don't have his feedback yet, however he is considering adding this check to enable/disable voice anonymisation. Sounds great to me.

**Comment by evilaliv3** [comment]
Thank you Javi.

So in your use case you will always implement clear voice recording ? have you evaluated which is the impact for the users what prefer to stay anonymous? how would you handle it?

**Comment by evilaliv3** [comment]
Thank you @JaviAlama 

Actually i think that by mistake i published an experiment that definitely is not audible.

Would you please retry now?

Yes, adding the possibility to record without filters remain a last resort i think as community we have the responsibility to set the guidance. At the moment i really do not think that recording a clear voice would be the correct path.

**Comment by JaviAlama** [comment]
> Thank you @JaviAlama
> 
> Actually i think that by mistake i published an experiment that definitely is not audible.
> 
> Would you please retry now?
> 
> Yes, adding the possibility to record without filters remain a last resort i think as community we have the responsibility to set the guidance. At the moment i really do not think that recording a clear voice would be the correct path.

Much better now, it is intelligible. I think this level of distortion is just right.

**Comment by evilaliv3** [comment]
Thank you Glauco!

Let's see wht the other think! 

\cc @marcomeneghin @elbill

**Comment by eleibr** [comment]
Hi @evilaliv3, we run into the same bug with versione **4.13.11**.
The recipient can only download the voice message to listen to it since the player doesn't work.
The whistleblower can't even download it.

Recipient:
![image](https://github.com/globaleaks/GlobaLeaks/assets/113996868/98e3f959-d951-4d8a-aa99-0d18a0c0007f)
![image](https://github.com/globaleaks/GlobaLeaks/assets/113996868/110ffc33-0336-4218-892f-d4eeda089f65)

Whistleblower:
![image](https://github.com/globaleaks/GlobaLeaks/assets/113996868/437a2352-8791-414d-b28b-8f59181fb9d1)
![image](https://github.com/globaleaks/GlobaLeaks/assets/113996868/018f24d1-db65-4753-8424-80dc64a692bb)

**Comment by eleibr** [comment]
Hi @evilaliv3, any update about this request?

**Comment by evilaliv3** [comment]
Hello @eleibr 

In the current release we have fixed the possibility for the recipient to listen to the recording.

We will also soon release an update to enable whistleblowers download their own files, included the recording of the audio file.

**Comment by eleibr** [comment]
Thanks a lot @evilaliv3

**Comment by evilaliv3** [comment]
Closing as the new release will include possibility for whistleblowers to listen to their own recordings.

**Comment by eleibr** [comment]
That's great, thanks @evilaliv3
