### ISSUE TITLE
Enforce redirect from IP address to server hostname causing issue

### ISSUE THREAD

**Issue by jurdajrd** [globaleaks/whistleblowing-software#3717]
### What version of GlobaLeaks are you using?

4.11.5 but want to update to 4.13.14

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, Android, iOS

### Describe the issue

We are using FortiGate Virtual Servers for whistleblowing. Which is forwarding Public IP and port (https://'PublicIP':1443) to internal IP and port (http://'InternalIP':80). Currently we are on version 4.11.5 but after updating to 4.13.14, we are facing issue that whistleblowing is not working. I think it is because in version 4.13.0 you released 'Enforce redirect from IP address to server hostname'. Is there some workaround for us please? 

### Proposed solution

Let user choose if they want to force redirect IP to server hostname or not.

**Comment by gianlucagilardi** [comment]
Since you are redirecting traffic to internalIP:80 i suspect the certificate handling for HTPPS is carried out by your Fortigate  instance, correct?

**Comment by jurdajrd** [comment]
Yes on Fortigate there is HTPPS cerificate whistleblowing.ourdomain.com.
![image](https://github.com/globaleaks/GlobaLeaks/assets/54391873/d91d1432-2c02-47ee-a2a7-fb01b8258d3a)

**Comment by gianlucagilardi** [comment]
Then you need to enable SSL passthrough (or proxying) in FortiGate to allow certificate handling by GL itself, set the hostname in the network tab in GL and configure  your fortigate to forward seamlessly all the traffic with DSTPORT 80 and 443. Then you either use the automatic or the manual certificate management in GL.

**Comment by jurdajrd** [comment]
I am now able to reach it locally, but I will not be able to reach it in a future. Because it will be redirecting me from LAN to hostname all the time. What is the point of this settings. Honestly I think I will stay on the old version.

**Comment by jurdajrd** [comment]
Or can I enable in GlobeLeaks port forwarding? 443 to 1443? Or change port here? We are running ubuntu, I am so into Linux.

**Comment by evilaliv3** [comment]
Thank you for your question @jurdajrd 

Actually some users, with the intent of improving the security of globaleaks recommended that the software should answer only on the hostname and this is why the redirect is happening,

Using a reverse proxy is not recommended but if you think we could implement a solution please feel free to propose it.
We do not recommend to keep the old version because this will means that your setup will become soon outdated.

**Comment by jurdajrd** [comment]
What would be the best way to get it working back again with newest version? It is working now like that. User put in browser https://‘WanIP’:1443 where fortigate handles certificate and foward it to http://‘LanIP’ where is whistleblowing located. After update it is located on port 443? In ubuntu or whistlblowing can I change port 443 to another?

**Comment by evilaliv3** [comment]
At the moment i do not think you have viable options.

It was a matter of luck that before it was working; actually globaleaks by design requires to be used on port 80 and 443 and many of its security measures and optimizations takes this into consideration.

**Comment by jurdajrd** [comment]
Okay, I will leave it on version 4.11.5 and do not update. Or can I update to version 4.12.9? I think there is no option for us to get it working as you said. Can I give you some requested  features which would be good for us and maybe for others?

**Comment by knchris** [comment]
how to add a hostname or public address?

**Comment by evilaliv3** [comment]
Do you still need support on this ticket?

**Comment by jurdajrd** [comment]
Hello, I figure it out how to get it working back again with the latest update 4.14.8. We use our own cerificate. My only question is how to add certificate for the next year please? Now certificate is valid until 30.03.2024.

![image](https://github.com/globaleaks/GlobaLeaks/assets/54391873/a9f24972-583d-4c15-84bb-d1ddc56bf102)

Thank you.

**Comment by evilaliv3** [comment]
@jurdajrd : i'm sorry i did not notice your last question.

To update you certificate you will just need to disable the configuration and load the new certificate.

Whenever the configruation will be disabled the system will offer you the self signed certificated that was generated for you at install time on your system.
