### ISSUE TITLE
Potential Log issue - whistlebloser seems to log in very often

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/whistleblowing-software#4011]
### What version of GlobaLeaks are you using?

4.14.18

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Havin a potential ogging issue. One site has a whistleblower who repeatedly seems to log in. I've attached an excerpt of the log
[auditlog_excerpt.csv](https://github.com/globaleaks/GlobaLeaks/files/14435890/auditlog_excerpt.csv)

Is there any explanation to this behaviour - and has it been reported any whre else? As far as I'm informed, logging in should not be able to be automated. Is there any session cookie, that can support relogin without entering the code?

**Comment by evilaliv3** [comment]
@schris-dk: To me these appears to be lecit login and logout by users.

There are no automatic logics of login/logout.
Sessions automatically expire but when they expire but the logout log happens when the user clicks the logout link

**Comment by schris-dk** [comment]
Hi!

Ive attached the full log of the incident – I just think it is remarkable, that the whistleblower has so many logins – is this norma, behaviour?

Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>


Fra: Giovanni Pellerano ***@***.***>
Sendt: 29. februar 2024 17:51
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Potential Log issue - whistlebloser seems to log in very often (Issue #4011)


Ekstern afsender

@schris-dk<https://github.com/schris-dk>: To me these appears to be lecit login and logout by users.

There are no automatic logics of login/logout.
Sessions automatically expire but when they expire but the logout log happens when the user clicks the logout link

**Comment by evilaliv3** [comment]
@schris-dk : Are you still noticing this behaviour?

**Comment by evilaliv3** [comment]
Thank you! Closing the ticket then!
