### ISSUE TITLE
Service failed to start after ubuntu update

### ISSUE THREAD

**Issue by enzoservice** [globaleaks/whistleblowing-software#4031]
### What version of GlobaLeaks are you using?

last

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

After Ubuntu update, service globaleaks failed to start with exit code 1 FAILED.
[E] Exception while running Tor
2024-03-18 08:56:02+0000 [-] Traceback (most recent call last):
2024-03-18 08:56:02+0000 [-] File "/usr/lib/python3/dist-packages/globaleaks/services/service.py", line 25, in run
2024-03-18 08:56:02+0000 [-] yield self.operation()
2024-03-18 08:56:02+0000 [-] twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2024-03-18 08:56:02+0000 [-] [E] exception mail suppressed for exception (<class 'twisted.internet.error.ConnectionLost'>) [reason: special exception]
2024-03-18 08:56:02+0000 [-] Stopping factory <Site object at 0x7f5fbfc9db10>
2024-03-18 08:56:02+0000 [-] Server Shut Down.
2024-03-18 08:56:05+0000 [-] twistd 22.1.0 (/usr/bin/python3 3.10.12) starting up.
2024-03-18 08:56:05+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2024-03-18 08:56:09+0000 [-] [E] Found an already initialized database version: 67

**Comment by evilaliv3** [comment]
Thank you @enzoservice for reporting this.

Would you please provide more details about the type of update that you have performed?

**Comment by enzoservice** [comment]
> Thank you @enzoservice for reporting this.
> 
> Would you please provide more details about the type of update that you have performed?

sudo apt update && apt upgrade
there were some updates of ubuntu (the last update was performed about two weeks ago)

**Comment by evilaliv3** [comment]
Grazie @enzoservice 

Se erano tutti aggiornamenti minori non vedo ragioni per cui adesso l'applicativo non stia partendo.


Proverei a riavviare la macchina e vedere se tutto riparte o meno.

Ti chiederei poi gentilmente di verificare con il comando dmesg se vedi comparire qualche errore relativo ad apparmor.

Parimenti ti chiederei di fornirmi il log di globaleaks post riavvio.

Grazie

**Comment by enzoservice** [comment]
Si, erano tutti aggiornamenti minori.. 
ho già riavviato la macchina un paio di volte ma nulla da fare, sempre stesso errore.. 
su dmesg non ho notato nulla di anomalo
[globaleaks.log](https://github.com/globaleaks/GlobaLeaks/files/14694076/globaleaks.log)

**Comment by evilaliv3** [comment]
Apparentemente la problematica sembra relativa a Tor che non riesce a partire.

**Comment by enzoservice** [comment]
sono riuscito ad avviare manualmente tor, ma il servizio globaleaks non parte comunque... stesso errore..

**Comment by evilaliv3** [comment]
Tor come processo eseguito indipendentemente non varia la situazione.

GlobaLeaks avvia un proprio sottoprocesso per poterlo controllare e per un qualche motivo non ci sta riuscendo.

**Comment by enzoservice** [comment]
questo è quello che vedo: 

root@GLOBALEAKS01:~# service globaleaks start
Job for globaleaks.service failed because the control process exited with error code.
See "systemctl status globaleaks.service" and "journalctl -xeu globaleaks.service" for details.
root@GLOBALEAKS01:~#
root@GLOBALEAKS01:~# service globaleaks start
Job for globaleaks.service failed because the control process exited with error code.
See "systemctl status globaleaks.service" and "journalctl -xeu globaleaks.service" for details.
root@GLOBALEAKS01:~# systemctl status globaleaks.service
× globaleaks.service - LSB: Start the GlobaLeaks server.
     Loaded: loaded (/lib/systemd/system/globaleaks.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-03-21 14:52:16 UTC; 1s ago
    Process: 5267 ExecStart=/etc/init.d/globaleaks start (code=exited, status=1/FAILURE)
        CPU: 1.285s

Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: globaleaks.service: Control process exited, code=exited, status=1/FAILURE
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: globaleaks.service: Failed with result 'exit-code'.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: Failed to start LSB: Start the GlobaLeaks server..
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: globaleaks.service: Consumed 1.285s CPU time.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: globaleaks.service: Scheduled restart job, restart counter is at 5.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: Stopped LSB: Start the GlobaLeaks server..
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: globaleaks.service: Consumed 1.285s CPU time.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: globaleaks.service: Start request repeated too quickly.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: globaleaks.service: Failed with result 'exit-code'.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: Failed to start LSB: Start the GlobaLeaks server..
root@GLOBALEAKS01:~# journalctl -xeu globaleaks.service
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit globaleaks.service completed and consumed the indicated resources.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: globaleaks.service: Scheduled restart job, restart counter is at 5.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ Automatic restarting of the unit globaleaks.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: Stopped LSB: Start the GlobaLeaks server..
░░ Subject: A stop job for unit globaleaks.service has finished
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A stop job for unit globaleaks.service has finished.
░░
░░ The job identifier is 7468 and the job result is done.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: globaleaks.service: Consumed 1.285s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit globaleaks.service completed and consumed the indicated resources.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: globaleaks.service: Start request repeated too quickly.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: globaleaks.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit globaleaks.service has entered the 'failed' state with result 'exit-code'.
Mar 21 14:52:16 GLOBALEAKS01 systemd[1]: Failed to start LSB: Start the GlobaLeaks server..
░░ Subject: A start job for unit globaleaks.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit globaleaks.service has finished with a failure.
░░
░░ The job identifier is 7468 and the job result is failed.
lines 4485-4525/4525 (END)

**Comment by enzoservice** [comment]
> @enzoservice would you please try to write `APPARMOR_SANDBOXING=0` in /etc/default/globaleaks and try to restart globaleaks?


così si è avviato

**Comment by evilaliv3** [comment]
ok, allora molto probabilmente il nuovo kernel che avete installato non è compatibile con apparmor
