### ISSUE TITLE
Hyphen before home page title (refering to "Bug in title line of the frontpage #3876")

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/whistleblowing-software#4060]
### What version of GlobaLeaks are you using?

4.15.0

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

I never got a solution for this issue. Using DevTools I can see, that he issue is based in the <div id= TitleBox> section :

**`<span data-ng-if="projectTitle &amp;&amp; pageTitle" class="TitleSeparator"> - </span>`**

![YLbSwgZ6xv](https://github.com/globaleaks/GlobaLeaks/assets/70965554/9c2003ed-243a-4aab-b59a-d13cba22692f)

### Proposed solution

A solution to this issue could be to change this line to one of the two below:

1: **`<span data-ng-if="pageTitle" </span>`** (Removing the Project Title and only showing the PageTitle)

2: **`<span data-ng-if="projectTitle &amp;&amp; pageTitle"  </span>`** (removing the TitleSeparator - then it is possible to ad the hyphen to the Project title, if it is needed)

**Comment by evilaliv3** [comment]
Thank you @schris-dk 

This should be fixed in release 5

Please let us know if you still notice some defects
