### ISSUE TITLE
Expiration dates in the auditlog are incorrectly saved in the db.

### ISSUE THREAD

**Issue by obinnaeye** [globaleaks/whistleblowing-software#4124]
### What version of GlobaLeaks are you using?

Checked out from `devel` branch.

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

When the expiration date is updated, the `prev_expiration_date` and `curr_expiration_date` saved as timestamps in the `auditlog` table are not correct. 
When you check the updated value in `expiration_date` in the `internaltips` table, you can see the correct one.

### Proposed solution

This bug is most-likely comming from `backend/globaleaks/handlers/recipient/rtip.py`. We need to fix the `postpone_expiration` function to save the correct timestamps.

**Comment by evilaliv3** [comment]
Thank you @obinnaeye for your support!
