### ISSUE TITLE
Fail to upgrade from 4.12.7 to 4.15.8

### ISSUE THREAD

**Issue by jussara-ti** [globaleaks/whistleblowing-software#4139]
### What version of GlobaLeaks are you using?

GlobaLeaks 4.12.7 under Debian11_x64  and Debian12_x64

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Hello there,

After upgrade GlobaLeaks from version **4.12.7** to **4.15.8**, I can't access the service anymore. 

Is show the message "**_ERR_TOO_MANY_REDIRECTS_**" in the Chrome and Firefox browser.

I had test using Debian11 and 12 x64.

If I do a new install, the service work perfect.

Is there a way to work around this fail?

**Comment by evilaliv3** [comment]
Hello!

Do you run any proxy in front of globaleaks?

**Comment by jussara-ti** [comment]
No, there is no proxy in front of globaleaks.

**Comment by evilaliv3** [comment]
Thank you.

Actually we are not aware of any bug on this matter.

Please feel free to share here or to me privately on community.globaleaks.org the address of the server and i may try to understand the reason.

**Comment by jussara-ti** [comment]
Hello,
The server is on your private subnet. 

How can I do sequential update on GlobaLeaks (4.13.x, 4.14.x)? to check if the problem still happening. 
If I use apt, just the last release is available. 

Thank's

**Comment by Hexdigest123** [comment]
Hello, you could potentially use the following official Docker image from GlobaLeaks:
https://hub.docker.com/r/globaleaks/globaleaks

As explained in the following issue: https://github.com/globaleaks/GlobaLeaks/issues/4148#issuecomment-2277182396

**Comment by evilaliv3** [comment]
Closing the ticket as stale. 

@jussara-ti : plaase feel free to open it again if you need further assistance.
