### ISSUE TITLE
we can't install globaleaks in a Docker container

### ISSUE THREAD

**Issue by ivanricolivares14** [globaleaks/whistleblowing-software#4148]
### What version of GlobaLeaks are you using?

latest / new installation

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

We are trying to install globaleaks in a docker container with a debian 12 system, we have downloaded the script install-globaleaks.sh as it says in the official documentation, but when it comes to connecting to the repository it seems that it cannot connect because the repository does not trust of the key. the error is the following:
fail_globaleaks1
globaleaks2
![image](https://github.com/user-attachments/assets/0188a587-1aa5-413e-b1c0-3a66d2c67de1)
![image](https://github.com/user-attachments/assets/b797ee1a-777b-4ad6-bc17-51f98ac205fb)

when execute the script:
Running: "apt-get -y install gnupg net-tools software-properties-common wget"... SUCCESS
Adding GlobaLeaks PGP key to trusted APT keys
Updating GlobaLeaks apt source.list in /etc/apt/sources.list.d/globaleaks.list ...
Running: "apt-get update -y"... SUCCESS
Running: "apt-get install globaleaks -y"... FAIL
Ouch! The installation failed.

when execute the command "apt-get update":
Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown. Could not handshake: Error in the certificate verificat
Reading package lists... Done
W: Failed to fetch http://deb.globaleaks.org/bookworm/InRelease Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unicate verification. [IP: 10.15.119.106 8080]
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by evilaliv3** [comment]
Thank you @ivanricolivares14 

Do you still encounter this issue?

p.s. are you aware that we release official docker images? 

https://hub.docker.com/r/globaleaks/globaleaks

**Comment by Hexdigest123** [comment]
Hello, you could potentially use the following official Docker image from GlobaLeaks: 
https://hub.docker.com/r/globaleaks/globaleaks

As explained in the following issue: https://github.com/globaleaks/GlobaLeaks/issues/4148#issuecomment-2277182396

**Comment by evilaliv3** [comment]
Closing as stale.

@ivanricolivares14 : please feel free to open a new ticket if you are still encountering issues.
