### ISSUE TITLE
handling of outlook safelink protection

### ISSUE THREAD

**Issue by FFD8FFE1** [globaleaks/whistleblowing-software#4159]
### Proposal

is it possible to make the  password reset link able to be active with outlook/defender safelink protection by enabeling the link to be "clicked" two times?

### Motivation and context

when we reset the users password for their globaleaks account they cant use the link, because its already been clicked (if they follow the link)

example       https://eur05.safelinks.protection.outlook.com/?url=...............................................................

**Comment by evilaliv3** [comment]
Hello @FFD8FFE1 

Actually tokens are valid till the user complete the password change so that they could be clicked multiple times without any problem as long that the password change is not completed.

I suspect then that you are encountering a complete different problem.

**Comment by evilaliv3** [comment]
Closing the ticket as stale.

@FFD8FFE1 : please feel free to reopen it if you still need assistance.
