### ISSUE TITLE
Carriage Return / Break at Customized Text

### ISSUE THREAD

**Issue by DAD405** [globaleaks/whistleblowing-software#4179]
### What version of GlobaLeaks are you using?

5.0.3 

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

In Settings - Text customisation 

 I just want to enter a Linebreak between 
"Have you already filed a report?" and "Enter your receipt."

In my old the settings I used  < / b r >  ( have to space it out here, parsed other way)
Now it shows "Have you already filed a report? < / b r > Enter your receipt."  on the Frontpage.
As far as I remember this worked some time ago, the Problem was brought to my attention today.

I have tried to achive this via differnt notations, all unlucky.
How can I get a simple linebreak now in a Customized text?

To be clear: This is no issue on other texts like Footer or Start-Page-texts as normal markdown is working.

### Proposed solution

Sorry no Solution.
Maybe document used markdown-variant

**Comment by evilaliv3** [comment]
Hello @DAD405 

Thank you, this was already notified by @javialama.

I'm fixing it and i will be including a patch in a release 5.0.4.

Your previous configurations will work like a charm!

Please note that a new line will be enough; using <br /> or other HTML instead is prevented (like in the previous releases)

**Comment by DAD405** [comment]
Thank you for clarification.
As i have the Issue only in one instance any other solution would be 
fine too.
it does not have t be html but fixing this might fix other installations to.

Thank you for your work
