### ISSUE TITLE
 Missing button to upload a file from the receiver

### ISSUE THREAD

**Issue by marcopvl** [globaleaks/whistleblowing-software#4181]
### What version of GlobaLeaks are you using?

5.0.4

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hi, 
the upload fuction was not working form the last version 5.0.3, like reporting in the issue #4178 , and now in the new version 5.0.4, the button was missing like you could see in the picture attached.
![image4](https://github.com/user-attachments/assets/796a8990-cebe-4cc6-bbb2-3736412f9a58)
Please could you check it ?

Thanks in advance

**Comment by evilaliv3** [comment]
Thank you for reporting this @marcopvl

**Comment by marcopvl** [comment]
The complete backoffice page, there will be like this one, we could see in the attached files
![image5](https://github.com/user-attachments/assets/e5841047-d376-4783-8b45-ea66ed0f8055)

or in the docs url:
https://docs.globaleaks.org/it/main/user/Recipient.html#access-a-report

Thanks in advance.
