### ISSUE TITLE
Extend subsites' search to domain names

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/whistleblowing-software#4182]
### What version of GlobaLeaks are you using?

5.0.4

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

The internal search feature - search for sub sites - have now become case sensitive., which a search shouldn't be :-)

### Proposed solution

make search field case insensitive

**Comment by evilaliv3** [comment]
Thank you @schris-dk 

Actually the search has been always been case sensitive, so that what you are proposing is more an enhancement than a bug report.

**Comment by schris-dk** [comment]
I’ve always been able to search case insensitive.

Could the issue be relating to only searching the “site name” and not the URL as well?

***@***.***

Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>


Tænk på miljøet - er det nødvendigt at printe mailen?
Fra: Giovanni Pellerano ***@***.***>
Sendt: 10. september 2024 12:55
Til: globaleaks/GLOBALEAKS ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GLOBALEAKS] Internal search of sub-sites are now case sensitive (Issue #4182)


Ekstern afsender

Thank you @schris-dk<https://github.com/schris-dk>

Actually the search has been always been case sensitive, so that what you are proposing is more an enhancement than a bug report.

**Comment by evilaliv3** [comment]
You are right @schris-dk , the search is case insensitive but applied only to the name at the moment.

**Comment by evilaliv3** [comment]
Implemented and search made case insensitive.

The correction will be included in minor release 5.0.12
