### ISSUE TITLE
Regression on reports search introduced in release 5.0.0

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/whistleblowing-software#4184]
### Proposal

This ticket is to track the implementation necessary for making reports' search cases insensitive

### Motivation and context

As reported on similar ticket like  https://github.com/globaleaks/GLOBALEAKS/issues/4128 and https://github.com/globaleaks/GLOBALEAKS/issues/4182 the search could be improved on many factors, expecially making it case insensitive.

**Comment by evilaliv3** [comment]
Actually after looking into details the situation i think that with the new client we could have added a regression and it is not a matter of improving the search to be case insensitive, it is just the search that it is not working since release 5.0.0

**Comment by JaviAlama** [comment]
As I commented on issue #4128 , currently when searching for reports from the search text box the results returned are not adequate. The search should only be performed on fields with text or user-readable data (comments, file names, labels, questionnaires, etc.).

On the other hand, it would be very useful to be able to filter by each of the fields that appear in the columns of the list of reports. In this way, it would be very easy to access a specific report or to show only those reports that are in a particular status or that have been received between two dates.

After testing the search box on versions 5.0.17 and 5.0.18 in projects with many reports (>2000) the results are **not satisfactory.**

I know that work is being done on this, but I think it is necessary to follow up on this functionality, which I consider essential.
