### ISSUE TITLE
Inability to complete questionnaire 

### ISSUE THREAD

**Issue by EDPBK** [globaleaks/whistleblowing-software#4188]
### What version of GlobaLeaks are you using?

5.0.6

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

upgrading from version 4.15.9 to version 5.0.6 we are unable to complete our questionnaire.
When we try to go from the 6th to the 7th page (last page) we get an error that we haven't answered a mandatory question that is on the last page. 
here attached you can find a copy of the questionnaire to import and check the reason for the error
![error](https://github.com/user-attachments/assets/ee838d40-c2b6-4703-97a6-cebc8697774b)

[Copy for Github.txt](https://github.com/user-attachments/files/16996173/Copy.for.Github.txt)

### Proposed solution

regressing to version 4.15.9 the bug is not present

**Comment by evilaliv3** [comment]
Thank you for your feedback.

this is a know bug that we are correcting.

We expect to be releasing a bugfixed version 5.0.7 by the weekend.

**Comment by evilaliv3** [comment]
@EDPBK : when you can would you please test .0.10 and let us know if it fixed your issue?

**Comment by evilaliv3** [comment]
Closing as the issue should be fixed in current release.
