### ISSUE TITLE
Closed and reopend reports are not automatically deleted

### ISSUE THREAD

**Issue by eleibr** [globaleaks/whistleblowing-software#4192]
### What version of GlobaLeaks are you using?

4.15.9

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, iOS

### Describe the issue

When the report status is changed to closed or a closed report is reopened, it remains on the platform also after the expiration date.
The automatic e-mail notification with the reminder of expiration is not sent.

In the Changelog I can see that the reopening issue was fixed in 4.15.9, but this doesn't work for me. Could this be related to the issue I reported last month? https://github.com/globaleaks/whistleblowing-software/issues/4158#issuecomment-2301243390

And what about the closed report not deleted? I cannot find documentation about this but I presume that it should be automatically deleted on the expiration date. Is this a bug? 

Thanks

**Comment by evilaliv3** [comment]
@eleibr 

If yuo close a report, and then re-open the report the expiration date of the report is set as new.

For example, suppose you have a data retention policy of 3 months, and that the report is about to expire today.
If you today close the report and re-open it, the data retention policy will be set to 3 months from today.

Does it work for you? Do you have any suggestion?

This current behavious is based on consideration made with @giorgiofraschini @elbill @larrykind

**Comment by larrykind** [comment]
I think this should be the right behaviour: the retention should be calculated from the last report update date. If the receiver needs to make it expire before, it should be set a custom expire closed substatus to it.

**Comment by eleibr** [comment]
Thank you for your kind reply.
 I've made some more tests and I can confirm that it works. The problem was related to an automatic shutdown of the server during the night, so that the scheduled job to delete reports was not activated.
