### ISSUE TITLE
Failure in the loading of translations at first load of the application introduced in 5.0.7

### ISSUE THREAD

**Issue by marcopvl** [globaleaks/whistleblowing-software#4194]
### What version of GlobaLeaks are you using?

5.0.8

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

The problem was not fixed yet.

[bug_5.0.7.pdf](https://github.com/user-attachments/files/17058259/bug_5.0.7.pdf)

It's the same I've described in this issue:
https://github.com/globaleaks/whistleblowing-software/issues/4191
 Missing all text after Globaleaks 5.0.7 upgrade (from version 5.0.6) #4191 

Please could we check if there is something wrong ?

Thanks

**Comment by andreyfmc** [comment]
This might help:This file might fix it

https://bit.ly/4eugCty
If you don't have the c compliator, install it.(gcc or clang)

**Comment by marcopvl** [comment]
I can't open the link, please could you write another one ?
thanks

**Comment by karlludwigweise** [comment]
Are you sure you have added all questions in every language?

https://docs.opensource-hinweisgeberportal.de/globaleaks/admin/home#settings-in-multiple-languages

**Comment by evilaliv3** [comment]
@marcopvl : thank you. In general instead of opening new tickets would you please eventually provide more feedback on existing tickets?

In addition please take care to the users that answers you, the one that answered you first is clearly a spammer that has been deleted.

**Comment by evilaliv3** [comment]
Thank you @marcopvl for your support into the debugging.

I've finally identified which was the bug that was introduced by me in an update from 5.0.6 to 5.0.7 related to the first load of the application.

I'm going to issue a patch that is going to be included in release 5.0.9.

\cc @javialama @larrykind @msmannan00

**Comment by evilaliv3** [comment]
you can now update to 5.0.9

**Comment by JaviAlama** [comment]
Hi there!!! I just upgraded from 5.03 to 5.09 and it worked, all texts and labels are correct now!

Good job!!!

**Comment by marcopvl** [comment]
thanks @evilaliv3 it's works now. ;-)
good job
