### ISSUE TITLE
The main language is always English, despite the change to another language

### ISSUE THREAD

**Issue by dawnog** [globaleaks/whistleblowing-software#4195]
### What version of GlobaLeaks are you using?

5.08

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Globaleaks is installed on a VPS running Debian 11
Although the only language set is Polish, in the application on html lang="en’ 
This causes the Chrome browser, to want to translate the page which is confusing for users and additionally the translation is wrong
How can this be changed? 
Please help

**Comment by evilaliv3** [comment]
Would you please try on 5.0.9?

**Comment by dawnog** [comment]
Thank you for your reply, a small error crept in . I have version 5.07 and I see the availability of update 5.08 . I will update and probably there will be an available 5.09 . Hope this helps

**Comment by evilaliv3** [comment]
Ok, closing the ticket for now.

Eventually if you continue to have issues on 5.0.10 please feel free to reopen it
