### ISSUE TITLE
new backup feature 

### ISSUE THREAD

**Issue by dawnog** [globaleaks/whistleblowing-software#4199]
### Proposal

I have several subdomains and would like to be able to backup selected subdomains and also selectively restore from the copies

### Motivation and context

we can easily imagine the need to restore data (after errors, crashes, conscious action) only for a specific subdomain, because from the restoration of data in other subdomains.
I also have no idea how to do it emergency - manually...

**Comment by evilaliv3** [comment]
Hello @dawnog , some developers are already trying to evaluate this extension but there still no work in progress.

Are you interested in developing this extention or do you have clients that could support the implementation financially?
