### ISSUE TITLE
Wrong translation on comments tab

### ISSUE THREAD

**Issue by AlainL88** [globaleaks/whistleblowing-software#4207]
### What version of GlobaLeaks are you using?

5.0.11

### What browser(s) are you seeing the problem on?

Firefox

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

The tab "only me" is not translated.
![immagine](https://github.com/user-attachments/assets/45006ef8-34d2-42bd-a44f-a5bca2fc000d)

**Comment by evilaliv3** [comment]
Thank you for reporting this @AlainL88 

We are going to fix this in release 5.0.12
