### ISSUE TITLE
Error update 4.11.15 to 5.0.11

### ISSUE THREAD

**Issue by AlbertoMPC** [globaleaks/whistleblowing-software#4208]
I am trying to update 4.11.15 version to the latest version 5.0.11 and when I do it, the website indicates that it is not available

Is it not possible to upgrade from this version to a higher one?

It tells me that the PGP signature is not correct, I have also tried to update it and then update, without success

Thanks

**Comment by evilaliv3** [comment]
Hello @AlbertoMPC , would you please run the following commands and paste here the result?

apt-get update
apt-get upgrade

Thank you

**Comment by AlbertoMPC** [comment]
apt-get update

Des:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Obj:2 http://us.archive.ubuntu.com/ubuntu jammy InRelease                     
Des:4 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]    
Obj:5 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Des:6 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [17,9 kB]
Ign:3 https://deb.globaleaks.org jammy/ InRelease                              
Obj:7 https://deb.globaleaks.org jammy/ Release       
Des:8 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [26,3 kB]
Descargados 301 kB en 2s (198 kB/s)      
Leyendo lista de paquetes... Hecho
W: http://deb.globaleaks.org/jammy/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

apt-get upgrade

Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
Calculando la actualización... Hecho
Se actualizarán los siguientes paquetes:
  globaleaks
1 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
Se necesita descargar 84,7 MB de archivos.
Se liberarán 1.954 kB después de esta operación.
¿Desea continuar? [S/n]

**Comment by AlbertoMPC** [comment]
I have tried again with a new copy of the production machine

apt-get update

leyendo lista de paquetes... Hecho
W: http://deb.globaleaks.org/jammy/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Se produjo un error durante la verificación de las firmas. El repositorio no está actualizado y se utilizarán los ficheros de índice antiguos. Error de GPG: https://deb.globaleaks.org/ jammy/ Release: Las siguientes firmas no fueron válidas: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <[info@globaleaks.org](mailto:info@globaleaks.org)>
W: Fallo al obtener http://deb.globaleaks.org/jammy/Release.gpg  Las siguientes firmas no fueron válidas: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <[info@globaleaks.org](mailto:info@globaleaks.org)>
W: No se han podido descargar algunos archivos de índice, se han omitido, o se han utilizado unos antiguos en su lugar.

apt-get upgrade

And I have performed a system update, reboot the system an make a snapshot of the machine

apt-get update (same result)

leyendo lista de paquetes... Hecho
W: http://deb.globaleaks.org/jammy/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Se produjo un error durante la verificación de las firmas. El repositorio no está actualizado y se utilizarán los ficheros de índice antiguos. Error de GPG: https://deb.globaleaks.org/ jammy/ Release: Las siguientes firmas no fueron válidas: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <[info@globaleaks.org](mailto:info@globaleaks.org)>
W: Fallo al obtener http://deb.globaleaks.org/jammy/Release.gpg  Las siguientes firmas no fueron válidas: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <[info@globaleaks.org](mailto:info@globaleaks.org)>
W: No se han podido descargar algunos archivos de índice, se han omitido, o se han utilizado unos antiguos en su lugar.

I have tried this

https://github.com/globaleaks/whistleblowing-software/issues/2985

curl -L https://deb.globaleaks.org/globaleaks.asc | sudo apt-key add
apt-get update && apt-get install globaleaks

The same result, same result, my globaleaks website is broken

root@imioincidencias:~# globaleaks status
WARNING: The current long term supported platform is Debian 12 (bookworm)
WARNING: It is recommended to use only this platform to ensure stability and security
WARNING: To upgrade your system consult: https://docs.globaleaks.org/en/main/user/admin/UpgradeGuide.html
[E] Could not reserve socket for 98 (error: Address already in use)
[E] Could not reserve socket for 98 (error: Address already in use)
[E] Could not reserve socket for 98 (error: Address already in use)
Going in background; log available at /var/globaleaks/log/globaleaks.log
Another twistd server is running, PID 5283

This could either be a previously started instance of your application or a
different application entirely. To start a new one, either run it in some other
directory, or use the --pidfile and --logfile parameters to avoid clashes.

**Comment by AlbertoMPC** [comment]
I finally managed to upgrade (with problems) in a fresh copy of machine 

I haven't upgraded anything in Ubuntu (2.04.5 LTS)

wget https://deb.globaleaks.org/install-globaleaks.sh
chmod 777 [install-globaleaks.sh](http://install-globaleaks.sh/)
./[install-globaleaks.sh](http://install-globaleaks.sh/)

The port has changed and the home page is not displayed correctly, I will open another issue

https://github.com/globaleaks/whistleblowing-software/issues/4213

**Comment by evilaliv3** [comment]
Thank you @AlbertoMPC 

I was traveling and not able to answer.

The issue here was that your system did not have the up to date keys for verifying our package.

Since you at least managed to update i will close this ticket and we can proceed on the other about the graphic design issues.
