### ISSUE TITLE
Direct channel links lose configuration when the user change language

### ISSUE THREAD

**Issue by esperti** [globaleaks/whistleblowing-software#4217]
### What version of GlobaLeaks are you using?

5.0.11

### What browser(s) are you seeing the problem on?

Firefox, All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

In https://mydemo.try.globaleaks.org I configured AZIENDA_IT as a recipient also for AZIENDA_ESTERO, each with its own channel and personalized questionnaire, duplicated by DEFAULT in turn duplicated by Globaleaks (not editable). I report and confirm that:
1 - from the UUID link of the AZIENDA_IT channel, the box to enter the number of the previously entered report does not appear
2 - by changing the language, the questionnaire that appears is different, that is, the default one and not the channel one and is still shown in Italian and not in the selected language. By re-selecting the language you see the translation but in any case the questionnaire is the default one and not the AZIENDA_IT one

**Comment by evilaliv3** [comment]
Thank you for your feedback @esperti 

We are evaluating possibilities to limi the language of the context to few languages but it was never a simple topic. We will find to find a strategy.

We will instead instad right away fixing the issue with the reset of the questionnaire to default when using a UUID link and changing the language and try to have the fix already included in the next minor release 5.0.12

**Comment by evilaliv3** [comment]
I've separated issue 1. creating a dedicated ticket: https://github.com/globaleaks/whistleblowing-software/issues/4218
If you can always try to keep topics separate.

**Comment by evilaliv3** [comment]
Here is the link where we are reproducing this issue: https://mydemo.try.globaleaks.org/#/submission?context=31d382db-78f2-432b-a998-ab572d5c0da4

**Comment by evilaliv3** [comment]
Fixed, the correction will be included starting from minor release 5.0.12
